package whitepages

// Request Fields
// Either
type Request struct {
	APIKey string `json:"api_key"`
	*RequestAddress
	EmailAddress string `json:"email_address",omitempty`
	IPAddress    string `json:"ip_address",omitempty`
	Name         string `json:"name",omitempty`
	Phone        string `json:"phone",omitempty`
}

type RequestAddress struct {
	PostalCode  string `json:"address.postal_code",omitempty`
	State       string `json:"address.state",omitempty`
	StreetLine1 string `json:"address.street_line_1",omitempty`
	City        string `json:"address_city",omitempty`
}

// LeadVerifyResponse is the full response that the Lead Verify API returns
// If any of the checks are left out of the request (query), those check structures will be nil.
type LeadVerifyResponse struct {
	AddressChecks      *AddressChecks      `json:"address_checks"`
	EmailAddressChecks *EmailAddressChecks `json:"email_address_checks"`
	IPAddressChecks    *IPAddressChecks    `json:"ip_address_checks"`
	NameChecks         *NameChecks         `json:"name_checks"`
	PhoneChecks        *PhoneChecks        `json:"phone_checks"`
	Errors             []*error            `json:"errors"`
	Request            Request             `json:"request"`
}

// AddressChecks is a structure that gives verification info about the address in the query
// No address given will return a null response.
type AddressChecks struct {
	AddressContactScore int      `json:"address_contact_score"`
	AddressToName       string   `json:"address_to_name"`
	IsActive            bool     `json:"is_active"`
	IsValid             bool     `json:"is_valid"`
	ResidentName        string   `json:"resident_name"`
	Error               error    `json:"error"`
	Warnings            []string `json:"warnings"`
}

// EmailAddressChecks is a structure that gives info about the validity email address in the query
// No email address given will return a null response.
type EmailAddressChecks struct {
	Diagnostics       []string `json:"diagnostics"`
	EmailContactScore int      `json:"email_contact_score"`
	EmailToName       string   `json:"email_to_name"`
	IsAutoGenerated   bool     `json:"is_autogenerated"`
	IsDisposable      bool     `json:"is_disposable"`
	IsValid           bool     `json:"is_valid"`
	RegisteredName    string   `json:"registered_name"`
	Error             error    `json:"error"`
	Warnings          []string `json:"warnings"`
}

// IPAddressChecks is a structure that gives info about the validity of the IP address in the query
// No IP address given in query will return a null response.
type IPAddressChecks struct {
	DistanceFromAddress float32      `json:"distance_from_address"`
	GeoLocation         *GeoLocation `json:"geolocation"`
	IsProxy             bool         `json:"is_proxy"`
	IsValid             bool         `json:"is_valid"`
	Error               error        `json:"error"`
	Warnings            []string     `json:"warnings"`
}

// NameChecks is a structure that gives info about the validity of the name in the query
// No name given will return a null response.
type NameChecks struct {
	CelebrityName bool     `json:"celebrity_name"`
	FakeName      bool     `json:"fake_name"`
	Error         error    `json:"error"`
	Warnings      []string `json:"warnings"`
}

// PhoneChecks is a structure that gives verification info about the phone in the query
// No phone given will return a null response.
type PhoneChecks struct {
	Error error `json:"error"`
}

// GeoLocation is just simple address info like city, state, country and continent code
type GeoLocation struct {
	CityName      string `json:"city_name"`
	ContinentCode string `json:"continent_code"`
	CountryCode   string `json:"country_code"`
	CountryName   string `json:"country_name"`
	PostalCode    string `json:"postal_code"`
}
